import type { Metadata } from "next";
import StreamContextProvider from "@/providers/StreamContextProvider";

export const metadata: Metadata = {
  title: "Video App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <StreamContextProvider>{children}</StreamContextProvider>
    </>
  );
}
